[package]
name = "fpga_hps_programmator_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fpga_hps_programmator = { path="../fpga_hps_programmator" }
